# Generated by Django 4.0 on 2022-01-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(verbose_name='اعلان ها')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('file', models.FileField(upload_to='upload/', verbose_name='فایل')),
            ],
        ),
    ]
