# Generated by Django 4.0 on 2022-01-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shield', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='data',
            field=models.TextField(blank=True, null=True, verbose_name='اعلان ها'),
        ),
        migrations.AlterField(
            model_name='postdata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/', verbose_name='فایل'),
        ),
    ]
